server:
  port: 8081
  servlet: #!!!
    context-path: /api
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    hibernate:
      ddl-auto:  #!!!validate
    properties:
      dialect: dialect=org.hibernate.dialect.SQLServerDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mypgdb
    username: postgres
    password: root